package com.java.class29;

public class ExceptionReview {
	public static void main(String[] args) {
		try {

		} catch (Exception e) {

		} finally {
			System.out.println("it's in finally");
		}
	}
}
